### ISSUE TITLE
Make network card visible on the host

### ISSUE THREAD

**Issue by georgp24** [mfld-fr/elks#18]
For testing one would need to send some data from the host to the network card. This way one could test the receive function. The card:
"ne2k_isa.0: index=0,type=nic,model=ne2k_isa,macaddr=52:54:00:12:34:56"
should show up on the host with ifconfig -a for this.

Since Marc-Francois knows Qemu in and out he could give some instructions how to do that. 

I was thinking along the lines of these instructions perhaps:
[https://en.wikibooks.org/wiki/QEMU/Networking](url)
[http://wiki.qemu-project.org/Features/HelperNetworking](url)

**Comment by mfld-fr** [comment]
The simplest way is to use the host-to-guest forwarding of the user VLAN, and dump the forwarded packets, with the options:

`-net user,hostfwd=tcp:127.0.0.1:2323-10.0.2.15:23 -net dump`

After starting QEMU, one can use telnet on the host and to try to connect to the redirected port on host side:

`telnet 127.0.0.1 2323`

The connection (at this stage of development on ELKS networking) will fails, but one can see in the dump the internal NAT router (10.2.0.2) trying to forward to the guest (10.0.2.15), starting with ARP requests to find the right MAC address where to actually send the packets for IP 10.0.2.15.

So the guest (actually KTCP) should first respond to that ARP requests, so the router could then forward the TCP packets from the host, and forward the replies to the telnet client on the host.

**Comment by georgp24** [comment]
I suggest that these instructions go into the proposed readme-ne2k file.
