### ISSUE TITLE
Qemu script

### ISSUE THREAD

**Issue by georgp24** [mfld-fr/elks#20]
As far as I am aware, it is "keyb=en-us" and not "keyb=us". However, en-us did not work for me, so it is better to specify "keyb=".

**Comment by georgp24** [comment]
My script looks like this: (you have to put -k into $keyb)

# Helper to run ELKS in QEMU

# Specify your QEMU system emulator here:
qemu=qemu-system-i386
#qemu=qemu-system-x86_64

# Specify your keyboard mapping here:
# keyb=-k en-us
# keyb=-k fr
keyb=
# Specify network debugging here:
netdebug=-net dump
#netdebug=

# Configure QEMU as pure ISA system

$qemu -nodefaults -name ELKS -monitor stdio -machine isapc -cpu 486 \
-m 1M $keyb -display sdl -vga cirrus -rtc base=utc -serial pty \
-net nic,model=ne2k_isa -net user $netdebug -fda elkscmd/full3

**Comment by mfld-fr** [comment]
Thanks for the improved script !
Added in `ne2k` branch.

**Comment by georgp24** [comment]
Sorry, had to add " ".
