### ISSUE TITLE
Menuconfig

### ISSUE THREAD

**Issue by georgp24** [mfld-fr/elks#21]
In the current version there is only one network device drivers option: "NE2K device driver". Please leave the other options and just add the NE2K device driver.

**Comment by mfld-fr** [comment]
Do you have another Ethernet device in mind ?

**Comment by georgp24** [comment]
The driver/network submenu did have items for unix domain sockets, slip, cslip, af_inet etc. These are gone away and there is just one item left, the ne2k device driver. The items which were available before should remain and just the ne2k driver added to the list of items.

**Comment by mfld-fr** [comment]
The options for the sockets are not any more in the "drivers" section. They were moved to the top menu as "general networking", as in Linux today. Merely because these options are not specific to the hardware, like the drivers.
