### ISSUE TITLE
kill command working?

### ISSUE THREAD

**Issue by georgp24** [mfld-fr/elks#22]
For developing ktcp it is necessary to kill the ktcp process and start it again.

Can you please try to execute the kill command with the "corrected" select.c? When I tried "kill 5 &" will still crash. Not so with the old select.c of version 0.2.0

**Comment by mfld-fr** [comment]
As this problem looks like rather linked to ELKS mainstream and not to any of my subprojects (ROM version and Ethernet), please report that problem in Jody's repository, as I did for https://github.com/jbruchon/elks/issues/55.

**Comment by georgp24** [comment]
Well, the kill command works fine now. Just tested it again.
