### ISSUE TITLE
Move ne2k.h

### ISSUE THREAD

**Issue by georgp24** [mfld-fr/elks#23]
Can you move ne2k.h to linuxmt so I can better include it with ktcp?

**Comment by mfld-fr** [comment]
That header file contains the declarations shared between the two parts of the NE2K driver (C and assembly). It (should) contains nothing related to userspace where `ktcp\ runs, as the driver exposes only the standard file interface (except some specific defines for ioctl() that are declared in `arch/ioctl.h`.

What do you need exactly from that header ?

**Comment by georgp24** [comment]
I saw that the ne2k-test.c program included the header and therefore included it as well. I will check if I really require it.

**Comment by mfld-fr** [comment]
The `ne2k-test.c` program is a unit test that targets my real SBC with specific interrupts, not the ELKS environment. I use it to test the low level NE2K code on a real Ethernet chip. Please ignore that program.

**Comment by georgp24** [comment]
I checked it, I do not need to include ne2k.h. You can close this.
